Documentation:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - Gemfile
    - config/**/*
    - db/**/*
    - Rakefile
    - spec/*
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/**/*
Style/StringLiterals:
  Exclude:
    - db/**/*
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/**/*
